apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: hello-dep
  name: hello-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-dep
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello-dep
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
